### ISSUE TITLE
Please fix NPE

### ISSUE THREAD

**Issue by Artemych** [StepicOrg/stepik-android#79]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
    at org.stepic.droid.ui.fragments.VideoStepFragment.showTime(VideoStepFragment.java:154)
    at org.stepic.droid.ui.fragments.VideoStepFragment.access$100(VideoStepFragment.java:44)
    at org.stepic.droid.ui.fragments.VideoStepFragment$2.onResourceReady(VideoStepFragment.java:143)
    at org.stepic.droid.ui.fragments.VideoStepFragment$2.onResourceReady(VideoStepFragment.java:134)
    at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:522)
    at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
    at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
    at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
    at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

As is too hard to build the project for checking, I think this is due to you didn't call Glide.clear(thumbnailImageView); in VideoStepFragment.onDestroyView(), as a result NPE occured.

You can reproduce this issue by fast swiping between video steps.

**Comment by KirillMakarov** [comment]
Thank you, it is fixed and will be released in few days
